spring.application.name=patient-service

# Postgres (Docker: patient-service-db, host port 5000 -> 5432, database db)
spring.datasource.url=jdbc:postgresql://localhost:5000/db
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

server.port=4000

logging.level.root=info
